pet/account/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('registration/', views.AccountRegistration.as_view(),
         name = 'investor_registration'),
    path('login/', views.AccountLogin.as_view(), name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),    
    path('update/', views.AccountChangeView.as_view(), name = 'account_update'),
    path('', views.accuont_view, name='account_view'),
]

pet/analys/urls.py
from django.urls import path
from . import views

app_name = 'analys'

urlpatterns = [
    path('add_mov_aver/<int:sec_id>/', views.add_moving_averages, name = 'add_moving_averages')
]

pet/pet/urls.py
from django.contrib import admin
from django.urls import path, include
import time 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('analys/', include('analys.urls', namespace= 'analys')),
    path('', include('shares.urls', namespace= 'shares')),    
]

pet/shares/urls.py
from django.urls import path

from . import views

app_name = 'shares'

urlpatterns = [
    path('', views.title_page, name = 'title_page'),
    path('securities/', views.all_securities, name = 'all_security_list'),
    path('<slug:slug>/', views.security_detail, name = 'security_detail'),
    
]

pet/account/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    
    date_of_birth = models.DateField(blank = True, null = True)

    photo = models.ImageField(upload_to= 'users/%Y/%m/%d', blank = True)

    def __str__(self):
        return f'Profile of {self.user.username}'

pet/analys/models.py
from django.db import models
import numpy as np
import numba
# Create your models here.

class MovingAverages(models.Model):
    name = models.CharField(max_length = 10)
    period = models.PositiveIntegerField()
    #styles ['solid', 'dot', 'dash', 'longdash', 'dashdot', 'longdashdot']
    linestyle = models.CharField(max_length = 20)
    color = models.CharField(max_length = 7)
    lineType = models.CharField(max_length = 3)

    def plot(self, sct, vol = None):
        n = self.period
        if self.lineType == 'EMA':
            K = 2/(n + 1)
            EMA = [sct[0]]
            for i in range(len(sct)):
                EMA.append(EMA[-1] + (K * (sct[i] - EMA[-1])))
            EMA.pop(0)
            return EMA
        elif self.lineType == 'SMA':
            SMA = np.array([sum(sct[i-n:i]) / n if i>=n else sct[i] for i in range(len(sct))])
            return SMA
        elif self.lineType == 'WMA':
            vol = np.asarray(vol)
            sct = np.asarray(sct)
            WMA = np.array([(sum(sct[i-n:i] * vol[i-n:i]) / sum(vol[i-n:i])) if i>=n else sct[i]
                    for i in range(len(sct))])
            return WMA
    
    
    def bollinger_bands(self, sct, sma):    
        n = self.period
        p = len(sma)
        s = np.array([(1/n * sum((sct[i-n:i] - sma[i])**2))**(1/2) if i>=n else 0\
                        for i in range(p)])
        s = s * 2
        bb_upper = [sma[i] + s[i] for i in range(p)]
        bb_lower = [sma[i] - s[i] for i in range(p)]
        return bb_upper, bb_lower
    

pet/shares/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.urls import reverse
from django.conf import settings
import apimoex, requests
import pandas as pd

# Create your models here.

class Security(models.Model):
    name = models.CharField(max_length = 300)
    short_name = models.CharField(max_length = 100)
    sec_id = models.CharField(max_length = 10)
    board = models.CharField(max_length = 4)
    slug = models.SlugField(max_length = 120)
    description = models.TextField(blank = True)

    trade_dates = ArrayField(models.DateField())
    price_all = ArrayField(models.FloatField())
    volume = ArrayField(models.BigIntegerField())

    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, 
            related_name= 'securities_liked',
            blank = True)

    class Meta:
        indexes = [models.Index(fields = ['name']), 
                   models.Index(fields = ['id', 'slug'])]
        ordering = ['short_name']
        verbose_name = 'security'
        verbose_name_plural = 'securities'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shares:security_detail', args = [self.slug])

    

pet/account/forms.py
from typing import Any
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django import forms
from django.contrib.auth.models import User

class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']
        field_classes = {"username": UsernameField}

pet/analys/forms.py
from django import forms

class MovingAveragesForm(forms.Form):
    period = forms.IntegerField()
    line_type = forms.ChoiceField(choices= [('SMA', 'SMA'), ('WMA', 'WMA'), ('EMA', 'EMA')])

pet/shares/forms.py
from django import forms

pet/account/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LoginView
from .forms import MyUserCreationForm
from django.contrib.auth.decorators import login_required
# Create your views here.


def accuont_view(request):
    return render(request, 'account/acc.html')

def logout_view(request):
    logout(request)
    return redirect('/')

class AccountRegistration(CreateView):
    template_name = 'account/registration.html'
    form_class = MyUserCreationForm
    success_url = reverse_lazy('account_view')
    
    def form_valid(self, form):
        result = super().form_valid(form)
        cd = form.cleaned_data
        user = authenticate(username = cd['username'],
                            password = cd['password1'])
        login(self.request, user)
        return result

class AccountLogin(LoginView):
    template_name = 'account/login.html'
    authentication_form = AuthenticationForm
    next_page = reverse_lazy('account_view')


class AccountChangeView(CreateView):
    template_name = 'account/account_update.html'
    form_class = UserChangeForm
    success_url = reverse_lazy('account_view')

pet/analys/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shares.models import Security
from .models import MovingAverages
from .forms import MovingAveragesForm
# Create your views here.

@require_POST
def add_moving_averages(request, sec_id):
    security = get_object_or_404(Security, id = sec_id)
    form = MovingAveragesForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        MovingAverages.objects.create(
            name = f"{cd['line_type']}{cd['period']}",
            period = cd['period'],
            linestyle = 'dot',
            color = 'pink',
            lineType = cd['line_type']
        )
    return redirect('shares:security_detail', slug = security.slug)

pet/shares/views.py
from django.shortcuts import render, get_object_or_404
from .moex_all import MOEX_session
from .models import Security
from analys.forms import MovingAveragesForm
from analys.models import MovingAverages
from analys.analys import analys_plot
from django.core.cache import cache
# Create your views here.

def title_page(request):
    securities = Security.objects.all()
    return render(request, 'shares/share/title_page.html', 
                  {'securities': securities})

def security_detail(request, slug) -> render:
    key = f'{slug}'
    security = cache.get(key)
    if not security:
        security = get_object_or_404(Security, slug = slug)
        cache.set(key, security)
   
    price, volume = security.price_all, security.volume
    dates = security.trade_dates
    fig_price = analys_plot(price, volume, dates = dates,items = MovingAverages.objects.all())
    line_price = fig_price.to_html(full_html = False, include_plotlyjs = False)

    moving_form = MovingAveragesForm()

    return render(request, 'shares/share/security_detail.html',
                  {'security': security,
                   'line_price': line_price,
                   'moving_form': moving_form})

def all_securities(request):
    moex_list = MOEX_session(request)
    #moex_list.securirties_update()
    return render(request, 'shares/share/all_securities.html', 
                  {'moex_list': moex_list})

pet/analys/templates/analys/info.html
{% extends "base.html" %}
{% block title %}Analys info{% endblock %}

{% block content %}

{% endblock %}

pet/shares/templates/shares/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}Shares{% endblock %}</title>
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <link href="{% static "css/base.css" %}" rel="stylesheet">
    </head>
    <div id="header">
        <h1><a href="/" class="logo">My Shares</a></h1>
    </div>
    <div id="subheader">
        <table>
            <tr>
                <td><a href="{% url "shares:title_page" %}">{% trans "Home" %}</a></td>                
                <td><a href="{% url "shares:all_security_list" %}" title="Список всех компаний торгующихся на MOEX">
                    {% trans "MoexList" %}</a></td>
                <td><a href="#">{% trans "Techanalysis" %}</a></td>
                

                <div id="menu">                    
                    <button class="profile" onclick=""><img src=""></button>
                    <ul class="menu-list">
                    {% if user.is_authenticated %}
                        <li><a href="{% url "account_view" %}">{% trans "Profile" %}</a></li>
                        <li><a href="{% url "logout" %}">{% trans "Logout" %}</a></li>
                    {% else %}
                        <li><a href="{% url "login" %}">{% trans "Log In" %}</a></li>
                        <li><a href="{% url "investor_registration" %}">
                            {% trans "Registration" %}
                        </a></li>
                    {% endif %}
                    </ul>                    
                </div>

                <div id="language-menu">
                    <button class="language">{{ language.name_local }}</button>
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    <ul class="languages-list">
                        {% for language in languages %}
                        <li>
                            <a href="/{{ language.code }}/"
                            {% if language.code == LANGUAGE_CODE %} class="selected"{% endif %}>
                                {{ language.name_local }}
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </tr>
        </table>
    </div>
    
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    
    <script>
        const menu = document.getElementById('menu');

        menu.addEventListener(
            'mouseenter', function (e) {
                menu.classList.toggle('show')
            }
        );
        
        menu.addEventListener(
            'mouseleave', function (e) {
                menu.classList.toggle('show')
            }
        );
        // menu.addEventListener(
        //     'click', function () {
        //         console.log('press')
        //     }
        // );

        const languageMenu = document.getElementById('language-menu');
        
        languageMenu.addEventListener(
            'click', function () {
               languageMenu.classList.toggle('show')
            }
        );

    </script>
</html>

pet/shares/templates/shares/share/all_securities.html
{% extends "shares/base.html" %}

{% load static %}

{% block title %}All securities{% endblock %}

{% block content %}
<div class="moex_list">
    <table>
        <caption>Список компаний торгуемых на Московоской бирже</caption>
        <tr>
            <th>Name</th>
            <th>Short name</th>
            <th>Secid</th>
            <th>Board</th>
        </tr>
        {% for secid in moex_list %}
            <tr>
                <td>{{ secid.name }}</td>
                <td>{{ secid.short_name }}</td>
                <td>{{ secid.secid }}</td>
                <td>{{ secid.board }}</td>
            </tr>
        {% endfor %}
    </table>>
</div>
{% endblock %}

pet/shares/templates/shares/share/security_detail.html
{% extends "shares/base.html" %}
{% load static %}

{% block title %}
Security
<script src="https://cdn.plot.ly/plotly-latest.min.js">
</script>
{% endblock %}

{% block content %}
<div class="detail">
    <h2>{{ security.name }} ({{ security.sec_id }})</h2>
    <p>Short name: {{ security.short_name }}<br>Board: {{ security.board }}</p>
    <p>{{ security.description }}</p>

    <div class="line">
        <h3>График {{ security.name }}</h3>
        {% autoescape off %}
    
        {{ line_price }}
    
        {% endautoescape %}
    </div>
    <div class="analys_forms">
        <h3>Инструменты технического анализа</h3>
        <h4>Скользящие средние</h4>
        <form action="{% url "analys:add_moving_averages" security.id %}" method="post">            
            {{ moving_form.line_type }} {{ moving_form.period }}
            {% csrf_token %}
            <input type="submit" name="button" value="Add">
        </form>
        <h4>Осциляторы</h4>
        <form>
            <p>RSI <input type="number" name="RSI"></p>
        </form>
    </div>
</div>
{% endblock %}

pet/shares/templates/shares/share/title_page.html
{% extends "shares/base.html" %}
{% load static %}

{% block title %}Title page{% endblock %}

{% block content %}
    <div id="sidebar">
        <h2>Листинг компаний</h2>
        <h3>Избранное</h3>
        <h3>Все</h3>
        <ul>
            {% for sec in securities %}
            <li><a href="{{ sec.get_absolute_url }}">{{ sec.short_name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div id="main">
        <div class="news">
            <h2>Новости</h2>
        </div>
        
    </div>
{% endblock %}

pet/shares/templates/shares/title_page.html
{% extends "shares/base.html" %}
{% load static %}

{% block title %}Title page{% endblock %}

{% block content %}
    <div id="sidebar">
        <h2>Листинг компаний</h2>
        <h3>Избранное</h3>
        <h3>Все</h3>
        <ul>
            {% for secid in moex_list %}
                <li><a href="/">{{ secid.short_name }}</a></li>
            {% endfor %}
        </ul>
        
    </div>
    <div id="main">
        <h2>This is first try to create web-site</h2>
    </div>
{% endblock %}